const tradicionales = [
  {
    title: "Napolitana",
    img: "assets/img/pizzas/pizza-napolitana.jpg",
    category: "Tradicionales",
    ingredients: "Tomate en rodaja y anchoas.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Jamon y Champiñones",
    img: "assets/img/pizzas/pizza-jamon-york.jpg",
    category: "Tradicionales",
    ingredients: "Jamón york y champiñones.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Tropical",
    img: "assets/img/pizzas/pizza-tropical.jpg",
    category: "Tradicionales",
    ingredients: "Jamón york y piña.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Vegetariana",
    img: "assets/img/pizzas/pizza-vegetariana.jpg",
    category: "Tradicionales",
    ingredients: "Verduras grilladas.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Mediterranea",
    img: "assets/img/pizzas/pizza-mediterranea.jpg",
    category: "Tradicionales",
    ingredients: "Pimiento, cebolla, atún, anchoas y olivas.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "4 Quesos",
    img: "assets/img/pizzas/pizza-4-quesos.jpg",
    category: "Tradicionales",
    ingredients: "Roquefort, parmesano, y rulo de cabra.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Barbacoa",
    img: "assets/img/pizzas/pizza-barbacoa.jpg",
    category: "Tradicionales",
    ingredients: "Carne picada, bacon y salsa barbacoa.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Mexicana",
    img: "assets/img/pizzas/pizza-mexicana.jpg",
    category: "Tradicionales",
    ingredients: "Pollo, maiz, cebolla y chile picante.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Carbonara",
    img: "assets/img/pizzas/pizza-carbonara.jpg",
    category: "Tradicionales",
    ingredients: "Bacon, huevo y salsa carbonara.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Caprese",
    img: "assets/img/pizzas/pizza-caprese.jpg",
    category: "Tradicionales",
    ingredients: "Rodajas de tomate, mozzarella fresca y albahaca.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Alemana",
    img: "assets/img/pizzas/pizza-alemana.jpg",
    category: "Tradicionales",
    ingredients: "Franfurt y bratwurst.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Catalana",
    img: "assets/img/pizzas/pizza-catalana.jpg",
    category: "Tradicionales",
    ingredients: "Pimientos rojos, champiñones, butifarra, ajo y perejil.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "4 Estaciones",
    img: "assets/img/pizzas/pizza-4-estaciones.jpg",
    category: "Tradicionales",
    ingredients: "Jamón york, verduras grilladas, roquefort, anchoas.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Atún y Cebolla",
    img: "assets/img/pizzas/pizza-atun-cebolla.jpg",
    category: "Tradicionales",
    ingredients: "Atún y cebolla.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
  {
    title: "Calzones",
    img: "assets/img/pizzas/pizza-calzone.jpg",
    category: "Tradicionales",
    ingredients: "A elegir.",
    description: "Pequeña 6€, Mediana 10€, Grande 15€",
    buttonText: "Pedir",
  },
];

export default tradicionales;
